export const coursesData = [
  {
    id: 1,
    year: "05/2017 - 06/2017",
    company: "Czechitas",
    name: "courses.1.name",
    description: "courses.1.description",
    anchor: "jak-na-web",
  },
  {
    id: 2,
    year: "09/2022 - 12/2022",
    company: "Czechitas",
    name: "courses.2.name",
    description: "courses.2.description",
    anchor: "stan-se-koderkou",
  },
  {
    id: 3,
    year: "01/2023 - 04/2023",
    company: "Czechitas",
    name: "courses.3.name",
    description: "courses.3.description",
    anchor: "javascript-1",
  },
  {
    id: 4,
    year: "04/2023 - 06/2023",
    company: "Czechitas",
    name: "courses.4.name",
    description: "courses.4.description",
    anchor: "javascript-2",
  },
  {
    id: 5,
    year: "10/2023 - 12/2023",
    company: "ReactGirls",
    name: "courses.5.name",
    description: "courses.5.description",
    anchor: "rg-mentoring",
  },
  {
    id: 6,
    year: "01/2024 - 04/2024",
    company: "Czechitas",
    name: "courses.6.name",
    description: "courses.6.description",
    anchor: "react-1",
  },
  {
    id: 7,
    year: "02/2024 - 04/2024",
    company: "Kódím.cz",
    name: "courses.7.name",
    description: "courses.7.description",
    anchor: "zaklady-ts",
  },
  {
    id: 8,
    year: "04/2024 - 06/2024",
    company: "Czechitas",
    name: "courses.8.name",
    description: "courses.8.description",
    anchor: "react-2",
  },
  {
    id: 9,
    year: "07/2024 - 08/2024",
    company: "Skillmea",
    name: "courses.9.name",
    description: "courses.9.description",
    anchor: "zaklady-next",
  },
  {
    id: 10,
    year: "09/2024 - 09/2024",
    company: "Czechitas",
    name: "courses.10.name",
    description: "courses.10.description",
    anchor: "figma",
  },
];