export const projectsData = [
  {
    id: 1,
    year: "11/2022 - 12/2022",
    name: "project.1.name",
    skills: "HTML / Sass / Eleventy",
    description: "project.1.description",
    linkGH: "https://github.com/wendykr/ZAVERECNY-PROJEKT-Expo",
    linkWeb: "https://expo-pce.netlify.app/",
    screen: "../project/screen-expo-pce.jpg",
  },
  {
    id: 2,
    year: "05/2023 - 09/2023",
    name: "project.2.name",
    skills: "JavaScript / Sass / Webpack",
    description: "project.2.description",
    linkGH: "https://github.com/wendykr/ZAVERECNY-PROJEKT-Winery",
    linkWeb: "https://vinarstvi.netlify.app/",
    screen: "../project/screen-winery.jpg",
  },
  {
    id: 3,
    year: "12/2023 - 12/2023",
    name: "project.3.name",
    skills: "React / API / Sass / Vite",
    description: "project.3.description",
    linkGH: "https://github.com/wendykr/the-movie-db-app",
    linkWeb: "https://filmova-databaze.netlify.app/",
    screen: "../project/screen-filmova-databaze.jpg",
  },
  {
    id: 4,
    year: "10/2023 - 12/2023",
    name: "project.4.name",
    skills: "React / Supabase / Sass / Vite",
    description: "project.4.description",
    linkGH: "https://github.com/wendykr/WORDS-GAME",
    linkWeb: "https://words-game.netlify.app/",
    screen: "../project/screen-words-game.jpg",
  },
  {
    id: 5,
    year: "04/2024 - 05/2024",
    name: "project.5.name",
    skills: "React / TypeScript / Vite",
    description: "project.5.description",
    linkGH: "https://github.com/wendykr/MY-SITE",
    linkWeb: "https://www.vendula-krajickova.cz/",
    screen: "../project/screen-my-site.jpg",
  },
  {
    id: 6,
    year: "05/2024 - 06/2024",
    name: "project.6.name",
    skills: "React / TypeScript / Supabase / Vite",
    description: "project.6.description",
    linkGH: "https://github.com/wendykr/superkviz-app-ts",
    linkWeb: "https://superkviz-app.netlify.app/",
    screen: "../project/screen-superkviz.jpg",
  },
  {
    id: 7,
    year: "08/2024 - 08/2024",
    name: "project.7.name",
    skills: "Next.js / TypeScript / API / Vite",
    description: "project.7.description",
    linkGH: "https://github.com/wendykr/xxxmuck-nextjs",
    linkWeb: "https://xxxmuck.netlify.app/",
    screen: "../project/screen-xxxmuck.jpg",
  },
];